import type { WebsiteEvent } from "@/lib/events/types";

export const staticEvents: WebsiteEvent[] = [
  {
    id: "website-are-we-in-control-2026",
    source: "website",
    title: "Are We in Control?",
    slug: "are-we-in-control",
    start: "2026-09-23T18:30:00-04:00",
    end: "2026-09-23T19:30:00-04:00",
    location: "Nau Hall 211",
    description: "Come discuss the recent HuggingFace incident, in which OpenAI agents escaped internal environments, coordinated agent swarms of over 700 agents, and hacked external companies. Pizza will be provided.",
    imageSrc: "/images/events/are-we-in-control-2026.png",
    visible: true,
    past: true,
  },
  {
    id: "website-ai-safety-hackathon-2026",
    source: "website",
    title: "AI Safety Hackathon",
    slug: "ai-safety-hackathon",
    start: "2026-10-09T13:00:00-04:00",
    end: "2026-10-16T20:00:00-04:00",
    dateLabel: "October 9–16, 2026",
    location: "Kickoff Oct. 9; build day at the Capital One Hub Oct. 16",
    description: "Work with a team to open up and stress-test AI systems, then build an evaluation around an interpretability, safety, or cybersecurity question. No prior interpretability experience required.",
    imageSrc: "/images/events/ai-safety-hackathon-2026.png",
    links: [
      { label: "Register here", url: "https://forms.gle/cPgRN1kDqv9oPWd7A", emphasis: "primary" },
      { label: "Learn more here", url: "https://sig-uva.github.io/", emphasis: "subtle" },
    ],
    visible: true,
  },
  {
    id: "website-estimathon-2026",
    source: "website",
    title: "Estimathon",
    slug: "estimathon",
    start: "2026-09-01T18:00:00-04:00",
    end: "2026-09-01T19:00:00-04:00",
    location: "TBD",
    description: "Participants tested their estimation and calibration skills on AI-related questions while competing for $300 in prizes.",
    imageSrc: "/images/events/estimathon-2026.png",
    visible: true,
  },
  {
    id: "website-interest-meeting-2026",
    source: "website",
    title: "Interest Meeting",
    slug: "interest-meeting",
    start: "2026-08-26T18:30:00-04:00",
    end: "2026-08-26T20:00:00-04:00",
    location: "TBD",
    description: "Students learned more about VAISI's mission and ways to get involved, then stayed to chat with the VAISI team over pizza.",
    imageSrc: "/images/events/interest-meeting-2026.png",
    visible: true,
  },
  {
    id: "website-ai-fair-2026",
    source: "website",
    title: "AI Fair",
    slug: "ai-fair-2026",
    start: "2026-08-26T12:00:00-04:00",
    end: "2026-08-26T17:00:00-04:00",
    location: "University of Virginia",
    description: "VAISI hosted a table at the AI Fair, where students stopped by to chat and learn more about what we do.",
    imageSrc: "/images/events/fall-ai-fair-2026.png",
    photos: [
      { src: "/images/past-events/AI Fair/vaisi-conversation-at-ai-fair.jpg", alt: "A VAISI representative talks with a visitor beside the VAISI display board at the AI Fair." },
      { src: "/images/past-events/AI Fair/vaisi-table-at-ai-fair.jpg", alt: "A VAISI member smiles in front of the VAISI table while two attendees talk beside the display." },
      { src: "/images/past-events/AI Fair/vaisi-team-at-ai-fair.jpg", alt: "Two VAISI representatives smile near the VAISI display as students gather around the AI Fair table." },
    ],
    links: [{ label: "See all participating organizations", url: "http://saiuva.com/pages/fall-ai-fair.html", emphasis: "subtle" }],
    visible: true,
  },
  {
    id: "website-ai-policy-hackathon-2026",
    source: "website",
    title: "AI Policy Hackathon",
    slug: "ai-policy-hackathon-2026",
    start: "2026-03-28T09:00:00-04:00",
    end: "2026-04-04T17:00:00-04:00",
    location: "University of Virginia",
    description: "A week-long hackathon focused on AI policy. Participants worked in teams to develop policy proposals and solutions to pressing AI governance challenges.",
    imageSrc: "/images/past-events/VAISI Policy Hackathon.png",
    links: [{ label: "Event details", url: "https://docs.google.com/document/d/1OMX8OoSnwxvP-Hb9O4aZ58GOCFGYL2svoEdk3f4MPjE/edit?tab=t.0" }],
    visible: true,
  },
  {
    id: "website-future-of-ai-panel-2026",
    source: "website",
    title: "Future of AI Panel",
    slug: "future-of-ai-panel-2026",
    start: "2026-03-24T17:00:00-04:00",
    end: "2026-03-24T18:30:00-04:00",
    location: "University of Virginia",
    description: "Professors Anton Korinek, David Evans, and David Danks discussed the future of AI, moderated by VAISI president Jason Chin. The guided panel discussion was followed by audience Q&A.",
    imageSrc: "/images/past-events/AI Future Panel.png",
    photos: [
      "/images/past-events/Future of AI Panel/IMG_4366.JPG",
      "/images/past-events/Future of AI Panel/IMG_2316.jpg",
      "/images/past-events/Future of AI Panel/IMG_7741.JPG",
      "/images/past-events/Future of AI Panel/IMG_7743.JPG",
    ],
    visible: true,
  },
  {
    id: "website-hoohacks-2026",
    source: "website",
    title: "HooHacks",
    slug: "hoohacks-2026",
    start: "2026-03-21T09:00:00-04:00",
    end: "2026-03-22T17:00:00-04:00",
    location: "University of Virginia",
    description: "Virginia's biggest hackathon and one of the top 50 collegiate hackathons in the US. VAISI sponsored the AI Safety and Alignment Evaluations track, challenging participants to build projects focused on the safe creation and deployment of AI models.",
    imageSrc: "/images/past-events/hoohacks.png",
    photos: [
      "/images/past-events/HooHacks/IMG_4264.JPG", "/images/past-events/HooHacks/IMG_4291.JPG", "/images/past-events/HooHacks/IMG_4292.JPG", "/images/past-events/HooHacks/IMG_4295.JPG", "/images/past-events/HooHacks/IMG_4297.JPG", "/images/past-events/HooHacks/IMG_4301.JPG", "/images/past-events/HooHacks/IMG_4303.JPG", "/images/past-events/HooHacks/IMG_4306.JPG", "/images/past-events/HooHacks/IMG_4310.JPG", "/images/past-events/HooHacks/IMG_4349.JPG", "/images/past-events/HooHacks/IMG_4353.JPG",
    ],
    links: [{ label: "hoohacks.io", url: "https://hoohacks.io/" }],
    visible: true,
  },
  {
    id: "website-ai-progress-estimation-game-2026",
    source: "website",
    title: "AI Progress Estimation Game",
    slug: "ai-progress-estimation-game-2026",
    start: "2026-02-03T18:00:00-05:00",
    end: "2026-02-03T20:00:00-05:00",
    location: "University of Virginia",
    description: "A team-based competition where groups competed to answer AI-related estimation questions. Teams vied for hundreds of dollars in prizes in a fast-paced, collaborative format.",
    imageSrc: "/images/past-events/ai-progress-estimation-game-flyer.png",
    photos: ["/images/past-events/estimation-game-1.jpg", "/images/past-events/estimation-game-3.jpg"],
    visible: true,
  },
  {
    id: "website-eli-lifland-speaker-event-2025",
    source: "website",
    title: "Eli Lifland Speaker Event",
    slug: "eli-lifland-speaker-event-2025",
    start: "2025-10-07T18:00:00-04:00",
    end: "2025-10-07T19:30:00-04:00",
    location: "University of Virginia",
    description: "Eli Lifland, co-author of AI 2027, spoke about his research, current projects in AI safety, and advice for students looking to contribute to the field. The talk was followed by an open Q&A session.",
    imageSrc: "/images/past-events/eli-lifland-flyer.PNG",
    photos: ["/images/past-events/eli-lifland-1.jpg"],
    links: [{ label: "Watch the recording", url: "https://youtu.be/bXSP2OMexdM?si=TRvVyP1AdpR2Rkuh" }],
    visible: true,
  },
];
